application: go-url
version: 1
runtime: go
api_version: go1

default_expiration: "1d"

handlers:
- url: /favicon.ico
  static_files: static/image/favicon.ico
  upload: static/image/favicon.ico
  login: required

- url: /js
  static_dir: static/javascript
  mime_type: application/javascript
  login: required

- url: /style
  static_dir: static/style
  mime_type: text/css
  login: required

- url: /image
  static_dir: static/image
  mime_type: image/png
  login: required

- url: /.*
  script: _go_app
  login: required

